// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package br.qikserve.posserviceproto.model.menu;

/**
 * Protobuf type {@code MenuResponse}
 */
public  final class MenuResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MenuResponse)
    MenuResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MenuResponse.newBuilder() to construct.
  private MenuResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MenuResponse() {
    root_ = java.util.Collections.emptyList();
    entities_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MenuResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MenuResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              root_ = new java.util.ArrayList<br.qikserve.posserviceproto.model.menu.PosEntityLink>();
              mutable_bitField0_ |= 0x00000001;
            }
            root_.add(
                input.readMessage(br.qikserve.posserviceproto.model.menu.PosEntityLink.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              entities_ = new java.util.ArrayList<br.qikserve.posserviceproto.model.menu.PosEntity>();
              mutable_bitField0_ |= 0x00000002;
            }
            entities_.add(
                input.readMessage(br.qikserve.posserviceproto.model.menu.PosEntity.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        root_ = java.util.Collections.unmodifiableList(root_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        entities_ = java.util.Collections.unmodifiableList(entities_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_MenuResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_MenuResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.qikserve.posserviceproto.model.menu.MenuResponse.class, br.qikserve.posserviceproto.model.menu.MenuResponse.Builder.class);
  }

  public static final int ROOT_FIELD_NUMBER = 1;
  private java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> root_;
  /**
   * <code>repeated .PosEntityLink root = 1;</code>
   */
  public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> getRootList() {
    return root_;
  }
  /**
   * <code>repeated .PosEntityLink root = 1;</code>
   */
  public java.util.List<? extends br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> 
      getRootOrBuilderList() {
    return root_;
  }
  /**
   * <code>repeated .PosEntityLink root = 1;</code>
   */
  public int getRootCount() {
    return root_.size();
  }
  /**
   * <code>repeated .PosEntityLink root = 1;</code>
   */
  public br.qikserve.posserviceproto.model.menu.PosEntityLink getRoot(int index) {
    return root_.get(index);
  }
  /**
   * <code>repeated .PosEntityLink root = 1;</code>
   */
  public br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder getRootOrBuilder(
      int index) {
    return root_.get(index);
  }

  public static final int ENTITIES_FIELD_NUMBER = 2;
  private java.util.List<br.qikserve.posserviceproto.model.menu.PosEntity> entities_;
  /**
   * <code>repeated .PosEntity entities = 2;</code>
   */
  public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntity> getEntitiesList() {
    return entities_;
  }
  /**
   * <code>repeated .PosEntity entities = 2;</code>
   */
  public java.util.List<? extends br.qikserve.posserviceproto.model.menu.PosEntityOrBuilder> 
      getEntitiesOrBuilderList() {
    return entities_;
  }
  /**
   * <code>repeated .PosEntity entities = 2;</code>
   */
  public int getEntitiesCount() {
    return entities_.size();
  }
  /**
   * <code>repeated .PosEntity entities = 2;</code>
   */
  public br.qikserve.posserviceproto.model.menu.PosEntity getEntities(int index) {
    return entities_.get(index);
  }
  /**
   * <code>repeated .PosEntity entities = 2;</code>
   */
  public br.qikserve.posserviceproto.model.menu.PosEntityOrBuilder getEntitiesOrBuilder(
      int index) {
    return entities_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < root_.size(); i++) {
      output.writeMessage(1, root_.get(i));
    }
    for (int i = 0; i < entities_.size(); i++) {
      output.writeMessage(2, entities_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < root_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, root_.get(i));
    }
    for (int i = 0; i < entities_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, entities_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.qikserve.posserviceproto.model.menu.MenuResponse)) {
      return super.equals(obj);
    }
    br.qikserve.posserviceproto.model.menu.MenuResponse other = (br.qikserve.posserviceproto.model.menu.MenuResponse) obj;

    if (!getRootList()
        .equals(other.getRootList())) return false;
    if (!getEntitiesList()
        .equals(other.getEntitiesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRootCount() > 0) {
      hash = (37 * hash) + ROOT_FIELD_NUMBER;
      hash = (53 * hash) + getRootList().hashCode();
    }
    if (getEntitiesCount() > 0) {
      hash = (37 * hash) + ENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntitiesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.qikserve.posserviceproto.model.menu.MenuResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.qikserve.posserviceproto.model.menu.MenuResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MenuResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MenuResponse)
      br.qikserve.posserviceproto.model.menu.MenuResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_MenuResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_MenuResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.qikserve.posserviceproto.model.menu.MenuResponse.class, br.qikserve.posserviceproto.model.menu.MenuResponse.Builder.class);
    }

    // Construct using br.qikserve.posserviceproto.model.menu.MenuResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRootFieldBuilder();
        getEntitiesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (rootBuilder_ == null) {
        root_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        rootBuilder_.clear();
      }
      if (entitiesBuilder_ == null) {
        entities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        entitiesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_MenuResponse_descriptor;
    }

    @java.lang.Override
    public br.qikserve.posserviceproto.model.menu.MenuResponse getDefaultInstanceForType() {
      return br.qikserve.posserviceproto.model.menu.MenuResponse.getDefaultInstance();
    }

    @java.lang.Override
    public br.qikserve.posserviceproto.model.menu.MenuResponse build() {
      br.qikserve.posserviceproto.model.menu.MenuResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.qikserve.posserviceproto.model.menu.MenuResponse buildPartial() {
      br.qikserve.posserviceproto.model.menu.MenuResponse result = new br.qikserve.posserviceproto.model.menu.MenuResponse(this);
      int from_bitField0_ = bitField0_;
      if (rootBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          root_ = java.util.Collections.unmodifiableList(root_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.root_ = root_;
      } else {
        result.root_ = rootBuilder_.build();
      }
      if (entitiesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          entities_ = java.util.Collections.unmodifiableList(entities_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.entities_ = entities_;
      } else {
        result.entities_ = entitiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.qikserve.posserviceproto.model.menu.MenuResponse) {
        return mergeFrom((br.qikserve.posserviceproto.model.menu.MenuResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.qikserve.posserviceproto.model.menu.MenuResponse other) {
      if (other == br.qikserve.posserviceproto.model.menu.MenuResponse.getDefaultInstance()) return this;
      if (rootBuilder_ == null) {
        if (!other.root_.isEmpty()) {
          if (root_.isEmpty()) {
            root_ = other.root_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRootIsMutable();
            root_.addAll(other.root_);
          }
          onChanged();
        }
      } else {
        if (!other.root_.isEmpty()) {
          if (rootBuilder_.isEmpty()) {
            rootBuilder_.dispose();
            rootBuilder_ = null;
            root_ = other.root_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rootBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRootFieldBuilder() : null;
          } else {
            rootBuilder_.addAllMessages(other.root_);
          }
        }
      }
      if (entitiesBuilder_ == null) {
        if (!other.entities_.isEmpty()) {
          if (entities_.isEmpty()) {
            entities_ = other.entities_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEntitiesIsMutable();
            entities_.addAll(other.entities_);
          }
          onChanged();
        }
      } else {
        if (!other.entities_.isEmpty()) {
          if (entitiesBuilder_.isEmpty()) {
            entitiesBuilder_.dispose();
            entitiesBuilder_ = null;
            entities_ = other.entities_;
            bitField0_ = (bitField0_ & ~0x00000002);
            entitiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntitiesFieldBuilder() : null;
          } else {
            entitiesBuilder_.addAllMessages(other.entities_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.qikserve.posserviceproto.model.menu.MenuResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.qikserve.posserviceproto.model.menu.MenuResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> root_ =
      java.util.Collections.emptyList();
    private void ensureRootIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        root_ = new java.util.ArrayList<br.qikserve.posserviceproto.model.menu.PosEntityLink>(root_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.qikserve.posserviceproto.model.menu.PosEntityLink, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder, br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> rootBuilder_;

    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> getRootList() {
      if (rootBuilder_ == null) {
        return java.util.Collections.unmodifiableList(root_);
      } else {
        return rootBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public int getRootCount() {
      if (rootBuilder_ == null) {
        return root_.size();
      } else {
        return rootBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLink getRoot(int index) {
      if (rootBuilder_ == null) {
        return root_.get(index);
      } else {
        return rootBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder setRoot(
        int index, br.qikserve.posserviceproto.model.menu.PosEntityLink value) {
      if (rootBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRootIsMutable();
        root_.set(index, value);
        onChanged();
      } else {
        rootBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder setRoot(
        int index, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder builderForValue) {
      if (rootBuilder_ == null) {
        ensureRootIsMutable();
        root_.set(index, builderForValue.build());
        onChanged();
      } else {
        rootBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder addRoot(br.qikserve.posserviceproto.model.menu.PosEntityLink value) {
      if (rootBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRootIsMutable();
        root_.add(value);
        onChanged();
      } else {
        rootBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder addRoot(
        int index, br.qikserve.posserviceproto.model.menu.PosEntityLink value) {
      if (rootBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRootIsMutable();
        root_.add(index, value);
        onChanged();
      } else {
        rootBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder addRoot(
        br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder builderForValue) {
      if (rootBuilder_ == null) {
        ensureRootIsMutable();
        root_.add(builderForValue.build());
        onChanged();
      } else {
        rootBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder addRoot(
        int index, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder builderForValue) {
      if (rootBuilder_ == null) {
        ensureRootIsMutable();
        root_.add(index, builderForValue.build());
        onChanged();
      } else {
        rootBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder addAllRoot(
        java.lang.Iterable<? extends br.qikserve.posserviceproto.model.menu.PosEntityLink> values) {
      if (rootBuilder_ == null) {
        ensureRootIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, root_);
        onChanged();
      } else {
        rootBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder clearRoot() {
      if (rootBuilder_ == null) {
        root_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rootBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public Builder removeRoot(int index) {
      if (rootBuilder_ == null) {
        ensureRootIsMutable();
        root_.remove(index);
        onChanged();
      } else {
        rootBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder getRootBuilder(
        int index) {
      return getRootFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder getRootOrBuilder(
        int index) {
      if (rootBuilder_ == null) {
        return root_.get(index);  } else {
        return rootBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public java.util.List<? extends br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> 
         getRootOrBuilderList() {
      if (rootBuilder_ != null) {
        return rootBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(root_);
      }
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder addRootBuilder() {
      return getRootFieldBuilder().addBuilder(
          br.qikserve.posserviceproto.model.menu.PosEntityLink.getDefaultInstance());
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder addRootBuilder(
        int index) {
      return getRootFieldBuilder().addBuilder(
          index, br.qikserve.posserviceproto.model.menu.PosEntityLink.getDefaultInstance());
    }
    /**
     * <code>repeated .PosEntityLink root = 1;</code>
     */
    public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder> 
         getRootBuilderList() {
      return getRootFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.qikserve.posserviceproto.model.menu.PosEntityLink, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder, br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> 
        getRootFieldBuilder() {
      if (rootBuilder_ == null) {
        rootBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            br.qikserve.posserviceproto.model.menu.PosEntityLink, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder, br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder>(
                root_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        root_ = null;
      }
      return rootBuilder_;
    }

    private java.util.List<br.qikserve.posserviceproto.model.menu.PosEntity> entities_ =
      java.util.Collections.emptyList();
    private void ensureEntitiesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        entities_ = new java.util.ArrayList<br.qikserve.posserviceproto.model.menu.PosEntity>(entities_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.qikserve.posserviceproto.model.menu.PosEntity, br.qikserve.posserviceproto.model.menu.PosEntity.Builder, br.qikserve.posserviceproto.model.menu.PosEntityOrBuilder> entitiesBuilder_;

    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntity> getEntitiesList() {
      if (entitiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entities_);
      } else {
        return entitiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public int getEntitiesCount() {
      if (entitiesBuilder_ == null) {
        return entities_.size();
      } else {
        return entitiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntity getEntities(int index) {
      if (entitiesBuilder_ == null) {
        return entities_.get(index);
      } else {
        return entitiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder setEntities(
        int index, br.qikserve.posserviceproto.model.menu.PosEntity value) {
      if (entitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntitiesIsMutable();
        entities_.set(index, value);
        onChanged();
      } else {
        entitiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder setEntities(
        int index, br.qikserve.posserviceproto.model.menu.PosEntity.Builder builderForValue) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        entities_.set(index, builderForValue.build());
        onChanged();
      } else {
        entitiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder addEntities(br.qikserve.posserviceproto.model.menu.PosEntity value) {
      if (entitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntitiesIsMutable();
        entities_.add(value);
        onChanged();
      } else {
        entitiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder addEntities(
        int index, br.qikserve.posserviceproto.model.menu.PosEntity value) {
      if (entitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntitiesIsMutable();
        entities_.add(index, value);
        onChanged();
      } else {
        entitiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder addEntities(
        br.qikserve.posserviceproto.model.menu.PosEntity.Builder builderForValue) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        entities_.add(builderForValue.build());
        onChanged();
      } else {
        entitiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder addEntities(
        int index, br.qikserve.posserviceproto.model.menu.PosEntity.Builder builderForValue) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        entities_.add(index, builderForValue.build());
        onChanged();
      } else {
        entitiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder addAllEntities(
        java.lang.Iterable<? extends br.qikserve.posserviceproto.model.menu.PosEntity> values) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entities_);
        onChanged();
      } else {
        entitiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder clearEntities() {
      if (entitiesBuilder_ == null) {
        entities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        entitiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public Builder removeEntities(int index) {
      if (entitiesBuilder_ == null) {
        ensureEntitiesIsMutable();
        entities_.remove(index);
        onChanged();
      } else {
        entitiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntity.Builder getEntitiesBuilder(
        int index) {
      return getEntitiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityOrBuilder getEntitiesOrBuilder(
        int index) {
      if (entitiesBuilder_ == null) {
        return entities_.get(index);  } else {
        return entitiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public java.util.List<? extends br.qikserve.posserviceproto.model.menu.PosEntityOrBuilder> 
         getEntitiesOrBuilderList() {
      if (entitiesBuilder_ != null) {
        return entitiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entities_);
      }
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntity.Builder addEntitiesBuilder() {
      return getEntitiesFieldBuilder().addBuilder(
          br.qikserve.posserviceproto.model.menu.PosEntity.getDefaultInstance());
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntity.Builder addEntitiesBuilder(
        int index) {
      return getEntitiesFieldBuilder().addBuilder(
          index, br.qikserve.posserviceproto.model.menu.PosEntity.getDefaultInstance());
    }
    /**
     * <code>repeated .PosEntity entities = 2;</code>
     */
    public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntity.Builder> 
         getEntitiesBuilderList() {
      return getEntitiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.qikserve.posserviceproto.model.menu.PosEntity, br.qikserve.posserviceproto.model.menu.PosEntity.Builder, br.qikserve.posserviceproto.model.menu.PosEntityOrBuilder> 
        getEntitiesFieldBuilder() {
      if (entitiesBuilder_ == null) {
        entitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            br.qikserve.posserviceproto.model.menu.PosEntity, br.qikserve.posserviceproto.model.menu.PosEntity.Builder, br.qikserve.posserviceproto.model.menu.PosEntityOrBuilder>(
                entities_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        entities_ = null;
      }
      return entitiesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MenuResponse)
  }

  // @@protoc_insertion_point(class_scope:MenuResponse)
  private static final br.qikserve.posserviceproto.model.menu.MenuResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.qikserve.posserviceproto.model.menu.MenuResponse();
  }

  public static br.qikserve.posserviceproto.model.menu.MenuResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MenuResponse>
      PARSER = new com.google.protobuf.AbstractParser<MenuResponse>() {
    @java.lang.Override
    public MenuResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MenuResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MenuResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MenuResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.qikserve.posserviceproto.model.menu.MenuResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

