// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package br.qikserve.posserviceproto.model.menu;

/**
 * Protobuf type {@code PosEntity}
 */
public  final class PosEntity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PosEntity)
    PosEntityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PosEntity.newBuilder() to construct.
  private PosEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PosEntity() {
    type_ = 0;
    id_ = "";
    name_ = "";
    description_ = "";
    image_ = "";
    plu_ = "";
    allergens_ = java.util.Collections.emptyList();
    links_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PosEntity();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PosEntity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 41: {

            price_ = input.readDouble();
            break;
          }
          case 48: {

            available_ = input.readBool();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            image_ = s;
            break;
          }
          case 65: {

            factor_ = input.readDouble();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            plu_ = s;
            break;
          }
          case 80: {

            alcohol_ = input.readBool();
            break;
          }
          case 88: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              allergens_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            allergens_.add(rawValue);
            break;
          }
          case 90: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                allergens_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              allergens_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              links_ = new java.util.ArrayList<br.qikserve.posserviceproto.model.menu.PosEntityLink>();
              mutable_bitField0_ |= 0x00000002;
            }
            links_.add(
                input.readMessage(br.qikserve.posserviceproto.model.menu.PosEntityLink.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        allergens_ = java.util.Collections.unmodifiableList(allergens_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        links_ = java.util.Collections.unmodifiableList(links_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_PosEntity_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_PosEntity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.qikserve.posserviceproto.model.menu.PosEntity.class, br.qikserve.posserviceproto.model.menu.PosEntity.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.PosEntityType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.PosEntityType type = 1;</code>
   * @return The type.
   */
  public br.qikserve.posserviceproto.model.menu.PosEntityType getType() {
    @SuppressWarnings("deprecation")
    br.qikserve.posserviceproto.model.menu.PosEntityType result = br.qikserve.posserviceproto.model.menu.PosEntityType.valueOf(type_);
    return result == null ? br.qikserve.posserviceproto.model.menu.PosEntityType.UNRECOGNIZED : result;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object description_;
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 5;
  private double price_;
  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  public double getPrice() {
    return price_;
  }

  public static final int AVAILABLE_FIELD_NUMBER = 6;
  private boolean available_;
  /**
   * <code>bool available = 6;</code>
   * @return The available.
   */
  public boolean getAvailable() {
    return available_;
  }

  public static final int IMAGE_FIELD_NUMBER = 7;
  private volatile java.lang.Object image_;
  /**
   * <code>string image = 7;</code>
   * @return The image.
   */
  public java.lang.String getImage() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image_ = s;
      return s;
    }
  }
  /**
   * <code>string image = 7;</code>
   * @return The bytes for image.
   */
  public com.google.protobuf.ByteString
      getImageBytes() {
    java.lang.Object ref = image_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      image_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FACTOR_FIELD_NUMBER = 8;
  private double factor_;
  /**
   * <code>double factor = 8;</code>
   * @return The factor.
   */
  public double getFactor() {
    return factor_;
  }

  public static final int PLU_FIELD_NUMBER = 9;
  private volatile java.lang.Object plu_;
  /**
   * <code>string plu = 9;</code>
   * @return The plu.
   */
  public java.lang.String getPlu() {
    java.lang.Object ref = plu_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      plu_ = s;
      return s;
    }
  }
  /**
   * <code>string plu = 9;</code>
   * @return The bytes for plu.
   */
  public com.google.protobuf.ByteString
      getPluBytes() {
    java.lang.Object ref = plu_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      plu_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALCOHOL_FIELD_NUMBER = 10;
  private boolean alcohol_;
  /**
   * <code>bool alcohol = 10;</code>
   * @return The alcohol.
   */
  public boolean getAlcohol() {
    return alcohol_;
  }

  public static final int ALLERGENS_FIELD_NUMBER = 11;
  private java.util.List<java.lang.Integer> allergens_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, br.qikserve.posserviceproto.model.menu.AllergenType> allergens_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, br.qikserve.posserviceproto.model.menu.AllergenType>() {
            public br.qikserve.posserviceproto.model.menu.AllergenType convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              br.qikserve.posserviceproto.model.menu.AllergenType result = br.qikserve.posserviceproto.model.menu.AllergenType.valueOf(from);
              return result == null ? br.qikserve.posserviceproto.model.menu.AllergenType.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @return A list containing the allergens.
   */
  public java.util.List<br.qikserve.posserviceproto.model.menu.AllergenType> getAllergensList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, br.qikserve.posserviceproto.model.menu.AllergenType>(allergens_, allergens_converter_);
  }
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @return The count of allergens.
   */
  public int getAllergensCount() {
    return allergens_.size();
  }
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @param index The index of the element to return.
   * @return The allergens at the given index.
   */
  public br.qikserve.posserviceproto.model.menu.AllergenType getAllergens(int index) {
    return allergens_converter_.convert(allergens_.get(index));
  }
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @return A list containing the enum numeric values on the wire for allergens.
   */
  public java.util.List<java.lang.Integer>
  getAllergensValueList() {
    return allergens_;
  }
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of allergens at the given index.
   */
  public int getAllergensValue(int index) {
    return allergens_.get(index);
  }
  private int allergensMemoizedSerializedSize;

  public static final int LINKS_FIELD_NUMBER = 12;
  private java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> links_;
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> getLinksList() {
    return links_;
  }
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  public java.util.List<? extends br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> 
      getLinksOrBuilderList() {
    return links_;
  }
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  public int getLinksCount() {
    return links_.size();
  }
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  public br.qikserve.posserviceproto.model.menu.PosEntityLink getLinks(int index) {
    return links_.get(index);
  }
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  public br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder getLinksOrBuilder(
      int index) {
    return links_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (type_ != br.qikserve.posserviceproto.model.menu.PosEntityType.ITEM.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, description_);
    }
    if (price_ != 0D) {
      output.writeDouble(5, price_);
    }
    if (available_ != false) {
      output.writeBool(6, available_);
    }
    if (!getImageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, image_);
    }
    if (factor_ != 0D) {
      output.writeDouble(8, factor_);
    }
    if (!getPluBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, plu_);
    }
    if (alcohol_ != false) {
      output.writeBool(10, alcohol_);
    }
    if (getAllergensList().size() > 0) {
      output.writeUInt32NoTag(90);
      output.writeUInt32NoTag(allergensMemoizedSerializedSize);
    }
    for (int i = 0; i < allergens_.size(); i++) {
      output.writeEnumNoTag(allergens_.get(i));
    }
    for (int i = 0; i < links_.size(); i++) {
      output.writeMessage(12, links_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != br.qikserve.posserviceproto.model.menu.PosEntityType.ITEM.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, description_);
    }
    if (price_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, price_);
    }
    if (available_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, available_);
    }
    if (!getImageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, image_);
    }
    if (factor_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, factor_);
    }
    if (!getPluBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, plu_);
    }
    if (alcohol_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, alcohol_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < allergens_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(allergens_.get(i));
      }
      size += dataSize;
      if (!getAllergensList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }allergensMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < links_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, links_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.qikserve.posserviceproto.model.menu.PosEntity)) {
      return super.equals(obj);
    }
    br.qikserve.posserviceproto.model.menu.PosEntity other = (br.qikserve.posserviceproto.model.menu.PosEntity) obj;

    if (type_ != other.type_) return false;
    if (!getId()
        .equals(other.getId())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (getAvailable()
        != other.getAvailable()) return false;
    if (!getImage()
        .equals(other.getImage())) return false;
    if (java.lang.Double.doubleToLongBits(getFactor())
        != java.lang.Double.doubleToLongBits(
            other.getFactor())) return false;
    if (!getPlu()
        .equals(other.getPlu())) return false;
    if (getAlcohol()
        != other.getAlcohol()) return false;
    if (!allergens_.equals(other.allergens_)) return false;
    if (!getLinksList()
        .equals(other.getLinksList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAvailable());
    hash = (37 * hash) + IMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getImage().hashCode();
    hash = (37 * hash) + FACTOR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFactor()));
    hash = (37 * hash) + PLU_FIELD_NUMBER;
    hash = (53 * hash) + getPlu().hashCode();
    hash = (37 * hash) + ALCOHOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAlcohol());
    if (getAllergensCount() > 0) {
      hash = (37 * hash) + ALLERGENS_FIELD_NUMBER;
      hash = (53 * hash) + allergens_.hashCode();
    }
    if (getLinksCount() > 0) {
      hash = (37 * hash) + LINKS_FIELD_NUMBER;
      hash = (53 * hash) + getLinksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.qikserve.posserviceproto.model.menu.PosEntity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.qikserve.posserviceproto.model.menu.PosEntity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PosEntity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PosEntity)
      br.qikserve.posserviceproto.model.menu.PosEntityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_PosEntity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_PosEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.qikserve.posserviceproto.model.menu.PosEntity.class, br.qikserve.posserviceproto.model.menu.PosEntity.Builder.class);
    }

    // Construct using br.qikserve.posserviceproto.model.menu.PosEntity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLinksFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      id_ = "";

      name_ = "";

      description_ = "";

      price_ = 0D;

      available_ = false;

      image_ = "";

      factor_ = 0D;

      plu_ = "";

      alcohol_ = false;

      allergens_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      if (linksBuilder_ == null) {
        links_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        linksBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.qikserve.posserviceproto.model.menu.MenuProtos.internal_static_PosEntity_descriptor;
    }

    @java.lang.Override
    public br.qikserve.posserviceproto.model.menu.PosEntity getDefaultInstanceForType() {
      return br.qikserve.posserviceproto.model.menu.PosEntity.getDefaultInstance();
    }

    @java.lang.Override
    public br.qikserve.posserviceproto.model.menu.PosEntity build() {
      br.qikserve.posserviceproto.model.menu.PosEntity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.qikserve.posserviceproto.model.menu.PosEntity buildPartial() {
      br.qikserve.posserviceproto.model.menu.PosEntity result = new br.qikserve.posserviceproto.model.menu.PosEntity(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      result.id_ = id_;
      result.name_ = name_;
      result.description_ = description_;
      result.price_ = price_;
      result.available_ = available_;
      result.image_ = image_;
      result.factor_ = factor_;
      result.plu_ = plu_;
      result.alcohol_ = alcohol_;
      if (((bitField0_ & 0x00000001) != 0)) {
        allergens_ = java.util.Collections.unmodifiableList(allergens_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.allergens_ = allergens_;
      if (linksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          links_ = java.util.Collections.unmodifiableList(links_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.links_ = links_;
      } else {
        result.links_ = linksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.qikserve.posserviceproto.model.menu.PosEntity) {
        return mergeFrom((br.qikserve.posserviceproto.model.menu.PosEntity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.qikserve.posserviceproto.model.menu.PosEntity other) {
      if (other == br.qikserve.posserviceproto.model.menu.PosEntity.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.getAvailable() != false) {
        setAvailable(other.getAvailable());
      }
      if (!other.getImage().isEmpty()) {
        image_ = other.image_;
        onChanged();
      }
      if (other.getFactor() != 0D) {
        setFactor(other.getFactor());
      }
      if (!other.getPlu().isEmpty()) {
        plu_ = other.plu_;
        onChanged();
      }
      if (other.getAlcohol() != false) {
        setAlcohol(other.getAlcohol());
      }
      if (!other.allergens_.isEmpty()) {
        if (allergens_.isEmpty()) {
          allergens_ = other.allergens_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAllergensIsMutable();
          allergens_.addAll(other.allergens_);
        }
        onChanged();
      }
      if (linksBuilder_ == null) {
        if (!other.links_.isEmpty()) {
          if (links_.isEmpty()) {
            links_ = other.links_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLinksIsMutable();
            links_.addAll(other.links_);
          }
          onChanged();
        }
      } else {
        if (!other.links_.isEmpty()) {
          if (linksBuilder_.isEmpty()) {
            linksBuilder_.dispose();
            linksBuilder_ = null;
            links_ = other.links_;
            bitField0_ = (bitField0_ & ~0x00000002);
            linksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLinksFieldBuilder() : null;
          } else {
            linksBuilder_.addAllMessages(other.links_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.qikserve.posserviceproto.model.menu.PosEntity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.qikserve.posserviceproto.model.menu.PosEntity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.PosEntityType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.PosEntityType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.PosEntityType type = 1;</code>
     * @return The type.
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityType getType() {
      @SuppressWarnings("deprecation")
      br.qikserve.posserviceproto.model.menu.PosEntityType result = br.qikserve.posserviceproto.model.menu.PosEntityType.valueOf(type_);
      return result == null ? br.qikserve.posserviceproto.model.menu.PosEntityType.UNRECOGNIZED : result;
    }
    /**
     * <code>.PosEntityType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(br.qikserve.posserviceproto.model.menu.PosEntityType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.PosEntityType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 5;</code>
     * @return The price.
     */
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 5;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private boolean available_ ;
    /**
     * <code>bool available = 6;</code>
     * @return The available.
     */
    public boolean getAvailable() {
      return available_;
    }
    /**
     * <code>bool available = 6;</code>
     * @param value The available to set.
     * @return This builder for chaining.
     */
    public Builder setAvailable(boolean value) {
      
      available_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool available = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailable() {
      
      available_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object image_ = "";
    /**
     * <code>string image = 7;</code>
     * @return The image.
     */
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string image = 7;</code>
     * @return The bytes for image.
     */
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string image = 7;</code>
     * @param value The image to set.
     * @return This builder for chaining.
     */
    public Builder setImage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      image_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string image = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearImage() {
      
      image_ = getDefaultInstance().getImage();
      onChanged();
      return this;
    }
    /**
     * <code>string image = 7;</code>
     * @param value The bytes for image to set.
     * @return This builder for chaining.
     */
    public Builder setImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      image_ = value;
      onChanged();
      return this;
    }

    private double factor_ ;
    /**
     * <code>double factor = 8;</code>
     * @return The factor.
     */
    public double getFactor() {
      return factor_;
    }
    /**
     * <code>double factor = 8;</code>
     * @param value The factor to set.
     * @return This builder for chaining.
     */
    public Builder setFactor(double value) {
      
      factor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double factor = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFactor() {
      
      factor_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object plu_ = "";
    /**
     * <code>string plu = 9;</code>
     * @return The plu.
     */
    public java.lang.String getPlu() {
      java.lang.Object ref = plu_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plu_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string plu = 9;</code>
     * @return The bytes for plu.
     */
    public com.google.protobuf.ByteString
        getPluBytes() {
      java.lang.Object ref = plu_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plu_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string plu = 9;</code>
     * @param value The plu to set.
     * @return This builder for chaining.
     */
    public Builder setPlu(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      plu_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string plu = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlu() {
      
      plu_ = getDefaultInstance().getPlu();
      onChanged();
      return this;
    }
    /**
     * <code>string plu = 9;</code>
     * @param value The bytes for plu to set.
     * @return This builder for chaining.
     */
    public Builder setPluBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      plu_ = value;
      onChanged();
      return this;
    }

    private boolean alcohol_ ;
    /**
     * <code>bool alcohol = 10;</code>
     * @return The alcohol.
     */
    public boolean getAlcohol() {
      return alcohol_;
    }
    /**
     * <code>bool alcohol = 10;</code>
     * @param value The alcohol to set.
     * @return This builder for chaining.
     */
    public Builder setAlcohol(boolean value) {
      
      alcohol_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool alcohol = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlcohol() {
      
      alcohol_ = false;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> allergens_ =
      java.util.Collections.emptyList();
    private void ensureAllergensIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        allergens_ = new java.util.ArrayList<java.lang.Integer>(allergens_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @return A list containing the allergens.
     */
    public java.util.List<br.qikserve.posserviceproto.model.menu.AllergenType> getAllergensList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, br.qikserve.posserviceproto.model.menu.AllergenType>(allergens_, allergens_converter_);
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @return The count of allergens.
     */
    public int getAllergensCount() {
      return allergens_.size();
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @param index The index of the element to return.
     * @return The allergens at the given index.
     */
    public br.qikserve.posserviceproto.model.menu.AllergenType getAllergens(int index) {
      return allergens_converter_.convert(allergens_.get(index));
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @param index The index to set the value at.
     * @param value The allergens to set.
     * @return This builder for chaining.
     */
    public Builder setAllergens(
        int index, br.qikserve.posserviceproto.model.menu.AllergenType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAllergensIsMutable();
      allergens_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @param value The allergens to add.
     * @return This builder for chaining.
     */
    public Builder addAllergens(br.qikserve.posserviceproto.model.menu.AllergenType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAllergensIsMutable();
      allergens_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @param values The allergens to add.
     * @return This builder for chaining.
     */
    public Builder addAllAllergens(
        java.lang.Iterable<? extends br.qikserve.posserviceproto.model.menu.AllergenType> values) {
      ensureAllergensIsMutable();
      for (br.qikserve.posserviceproto.model.menu.AllergenType value : values) {
        allergens_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllergens() {
      allergens_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @return A list containing the enum numeric values on the wire for allergens.
     */
    public java.util.List<java.lang.Integer>
    getAllergensValueList() {
      return java.util.Collections.unmodifiableList(allergens_);
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of allergens at the given index.
     */
    public int getAllergensValue(int index) {
      return allergens_.get(index);
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of allergens at the given index.
     * @return This builder for chaining.
     */
    public Builder setAllergensValue(
        int index, int value) {
      ensureAllergensIsMutable();
      allergens_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @param value The enum numeric value on the wire for allergens to add.
     * @return This builder for chaining.
     */
    public Builder addAllergensValue(int value) {
      ensureAllergensIsMutable();
      allergens_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .AllergenType allergens = 11;</code>
     * @param values The enum numeric values on the wire for allergens to add.
     * @return This builder for chaining.
     */
    public Builder addAllAllergensValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureAllergensIsMutable();
      for (int value : values) {
        allergens_.add(value);
      }
      onChanged();
      return this;
    }

    private java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> links_ =
      java.util.Collections.emptyList();
    private void ensureLinksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        links_ = new java.util.ArrayList<br.qikserve.posserviceproto.model.menu.PosEntityLink>(links_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.qikserve.posserviceproto.model.menu.PosEntityLink, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder, br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> linksBuilder_;

    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> getLinksList() {
      if (linksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(links_);
      } else {
        return linksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public int getLinksCount() {
      if (linksBuilder_ == null) {
        return links_.size();
      } else {
        return linksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLink getLinks(int index) {
      if (linksBuilder_ == null) {
        return links_.get(index);
      } else {
        return linksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder setLinks(
        int index, br.qikserve.posserviceproto.model.menu.PosEntityLink value) {
      if (linksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinksIsMutable();
        links_.set(index, value);
        onChanged();
      } else {
        linksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder setLinks(
        int index, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder builderForValue) {
      if (linksBuilder_ == null) {
        ensureLinksIsMutable();
        links_.set(index, builderForValue.build());
        onChanged();
      } else {
        linksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder addLinks(br.qikserve.posserviceproto.model.menu.PosEntityLink value) {
      if (linksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinksIsMutable();
        links_.add(value);
        onChanged();
      } else {
        linksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder addLinks(
        int index, br.qikserve.posserviceproto.model.menu.PosEntityLink value) {
      if (linksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLinksIsMutable();
        links_.add(index, value);
        onChanged();
      } else {
        linksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder addLinks(
        br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder builderForValue) {
      if (linksBuilder_ == null) {
        ensureLinksIsMutable();
        links_.add(builderForValue.build());
        onChanged();
      } else {
        linksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder addLinks(
        int index, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder builderForValue) {
      if (linksBuilder_ == null) {
        ensureLinksIsMutable();
        links_.add(index, builderForValue.build());
        onChanged();
      } else {
        linksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder addAllLinks(
        java.lang.Iterable<? extends br.qikserve.posserviceproto.model.menu.PosEntityLink> values) {
      if (linksBuilder_ == null) {
        ensureLinksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, links_);
        onChanged();
      } else {
        linksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder clearLinks() {
      if (linksBuilder_ == null) {
        links_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        linksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public Builder removeLinks(int index) {
      if (linksBuilder_ == null) {
        ensureLinksIsMutable();
        links_.remove(index);
        onChanged();
      } else {
        linksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder getLinksBuilder(
        int index) {
      return getLinksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder getLinksOrBuilder(
        int index) {
      if (linksBuilder_ == null) {
        return links_.get(index);  } else {
        return linksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public java.util.List<? extends br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> 
         getLinksOrBuilderList() {
      if (linksBuilder_ != null) {
        return linksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(links_);
      }
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder addLinksBuilder() {
      return getLinksFieldBuilder().addBuilder(
          br.qikserve.posserviceproto.model.menu.PosEntityLink.getDefaultInstance());
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder addLinksBuilder(
        int index) {
      return getLinksFieldBuilder().addBuilder(
          index, br.qikserve.posserviceproto.model.menu.PosEntityLink.getDefaultInstance());
    }
    /**
     * <code>repeated .PosEntityLink links = 12;</code>
     */
    public java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder> 
         getLinksBuilderList() {
      return getLinksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.qikserve.posserviceproto.model.menu.PosEntityLink, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder, br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> 
        getLinksFieldBuilder() {
      if (linksBuilder_ == null) {
        linksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            br.qikserve.posserviceproto.model.menu.PosEntityLink, br.qikserve.posserviceproto.model.menu.PosEntityLink.Builder, br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder>(
                links_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        links_ = null;
      }
      return linksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PosEntity)
  }

  // @@protoc_insertion_point(class_scope:PosEntity)
  private static final br.qikserve.posserviceproto.model.menu.PosEntity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.qikserve.posserviceproto.model.menu.PosEntity();
  }

  public static br.qikserve.posserviceproto.model.menu.PosEntity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PosEntity>
      PARSER = new com.google.protobuf.AbstractParser<PosEntity>() {
    @java.lang.Override
    public PosEntity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PosEntity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PosEntity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PosEntity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.qikserve.posserviceproto.model.menu.PosEntity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

