// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package br.qikserve.posserviceproto.model.menu;

public interface PosEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PosEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.PosEntityType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.PosEntityType type = 1;</code>
   * @return The type.
   */
  br.qikserve.posserviceproto.model.menu.PosEntityType getType();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>bool available = 6;</code>
   * @return The available.
   */
  boolean getAvailable();

  /**
   * <code>string image = 7;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <code>string image = 7;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <code>double factor = 8;</code>
   * @return The factor.
   */
  double getFactor();

  /**
   * <code>string plu = 9;</code>
   * @return The plu.
   */
  java.lang.String getPlu();
  /**
   * <code>string plu = 9;</code>
   * @return The bytes for plu.
   */
  com.google.protobuf.ByteString
      getPluBytes();

  /**
   * <code>bool alcohol = 10;</code>
   * @return The alcohol.
   */
  boolean getAlcohol();

  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @return A list containing the allergens.
   */
  java.util.List<br.qikserve.posserviceproto.model.menu.AllergenType> getAllergensList();
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @return The count of allergens.
   */
  int getAllergensCount();
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @param index The index of the element to return.
   * @return The allergens at the given index.
   */
  br.qikserve.posserviceproto.model.menu.AllergenType getAllergens(int index);
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @return A list containing the enum numeric values on the wire for allergens.
   */
  java.util.List<java.lang.Integer>
  getAllergensValueList();
  /**
   * <code>repeated .AllergenType allergens = 11;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of allergens at the given index.
   */
  int getAllergensValue(int index);

  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  java.util.List<br.qikserve.posserviceproto.model.menu.PosEntityLink> 
      getLinksList();
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  br.qikserve.posserviceproto.model.menu.PosEntityLink getLinks(int index);
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  int getLinksCount();
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  java.util.List<? extends br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder> 
      getLinksOrBuilderList();
  /**
   * <code>repeated .PosEntityLink links = 12;</code>
   */
  br.qikserve.posserviceproto.model.menu.PosEntityLinkOrBuilder getLinksOrBuilder(
      int index);
}
