// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package br.qikserve.posserviceproto.model.menu;

public interface PosEntityLinkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PosEntityLink)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.PosEntityType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.PosEntityType type = 2;</code>
   * @return The type.
   */
  br.qikserve.posserviceproto.model.menu.PosEntityType getType();
}
