// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: menu.proto

package br.qikserve.posserviceproto.model.menu;

/**
 * Protobuf enum {@code PosEntityType}
 */
public enum PosEntityType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ITEM = 0;</code>
   */
  ITEM(0),
  /**
   * <code>CATEGORY = 1;</code>
   */
  CATEGORY(1),
  /**
   * <code>MODIFIERS = 2;</code>
   */
  MODIFIERS(2),
  /**
   * <code>INGREDIENTS = 3;</code>
   */
  INGREDIENTS(3),
  /**
   * <code>CROSS_SELLS = 4;</code>
   */
  CROSS_SELLS(4),
  /**
   * <code>COMBO_MEAL = 5;</code>
   */
  COMBO_MEAL(5),
  /**
   * <code>COMBO_ITEM = 6;</code>
   */
  COMBO_ITEM(6),
  /**
   * <code>SIZED_ITEM = 7;</code>
   */
  SIZED_ITEM(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ITEM = 0;</code>
   */
  public static final int ITEM_VALUE = 0;
  /**
   * <code>CATEGORY = 1;</code>
   */
  public static final int CATEGORY_VALUE = 1;
  /**
   * <code>MODIFIERS = 2;</code>
   */
  public static final int MODIFIERS_VALUE = 2;
  /**
   * <code>INGREDIENTS = 3;</code>
   */
  public static final int INGREDIENTS_VALUE = 3;
  /**
   * <code>CROSS_SELLS = 4;</code>
   */
  public static final int CROSS_SELLS_VALUE = 4;
  /**
   * <code>COMBO_MEAL = 5;</code>
   */
  public static final int COMBO_MEAL_VALUE = 5;
  /**
   * <code>COMBO_ITEM = 6;</code>
   */
  public static final int COMBO_ITEM_VALUE = 6;
  /**
   * <code>SIZED_ITEM = 7;</code>
   */
  public static final int SIZED_ITEM_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PosEntityType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PosEntityType forNumber(int value) {
    switch (value) {
      case 0: return ITEM;
      case 1: return CATEGORY;
      case 2: return MODIFIERS;
      case 3: return INGREDIENTS;
      case 4: return CROSS_SELLS;
      case 5: return COMBO_MEAL;
      case 6: return COMBO_ITEM;
      case 7: return SIZED_ITEM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PosEntityType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PosEntityType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PosEntityType>() {
          public PosEntityType findValueByNumber(int number) {
            return PosEntityType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return br.qikserve.posserviceproto.model.menu.MenuProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final PosEntityType[] VALUES = values();

  public static PosEntityType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PosEntityType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:PosEntityType)
}

