// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package br.qikserve.posserviceproto.service;

public final class ServiceProtos {
  private ServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021userservice.proto\032\013login.proto2S\n\013User" +
      "Service\022$\n\005login\022\r.LoginRequest\032\014.APIRes" +
      "ponse\022\036\n\006logout\022\006.Empty\032\014.APIResponseB6\n" +
      "#br.qikserve.posserviceproto.serviceB\rSe" +
      "rviceProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          br.qikserve.posserviceproto.model.login.LoginProtos.getDescriptor(),
        });
    br.qikserve.posserviceproto.model.login.LoginProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
