// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package br.qikserve.posserviceproto.model.login;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
